import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { PopupProvider, ReactQueryClientProvider } from '@/shared/providers';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { AuthProvider } from '@/entities/user';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <title>TZ task</title>
    </head>
    <ReactQueryClientProvider>
      <AuthProvider>
        <body
          className={`${geistSans.variable} antialiased`}
        >
        <PopupProvider>
          <div className={'w-full max-w-[1200px] mx-auto py-10'}>
            {children}
          </div>
        </PopupProvider>

        <ToastContainer />

        </body>
      </AuthProvider>
    </ReactQueryClientProvider>
    </html>
  );
}
